//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFix_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen_De_Reparaciones
    {
        public int id_pieza_a_reparar { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_empleado_a_cargo { get; set; }
        public Nullable<int> id_estado_de_la_pieza { get; set; }
        public string descripcion_de_la_averia { get; set; }
        public Nullable<double> monto_acordado { get; set; }
        public Nullable<System.DateTime> fecha_de_la_alamacenamiento { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual estados_de_las_Piezas estados_de_las_Piezas { get; set; }
    }
}
