//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFix_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class estados_de_las_Piezas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public estados_de_las_Piezas()
        {
            this.Almacen_De_Reparaciones = new HashSet<Almacen_De_Reparaciones>();
        }
    
        public int id_estado { get; set; }
        public string name_estado { get; set; }
        public string desripcion_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Almacen_De_Reparaciones> Almacen_De_Reparaciones { get; set; }
    }
}
