//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFix_Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FixFastDbEntities : DbContext
    {
        public FixFastDbEntities()
            : base("name=FixFastDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Almacen_De_Reparaciones> Almacen_De_Reparaciones { get; set; }
        public virtual DbSet<categorias> categorias { get; set; }
        public virtual DbSet<citas> citas { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<estados_de_las_Piezas> estados_de_las_Piezas { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<puestos> puestos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
