//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFix_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int id_productos { get; set; }
        public Nullable<int> id_categria { get; set; }
        public string name_producto { get; set; }
        public string descripcion { get; set; }
        public string marca_del_producto { get; set; }
        public double precio_unidad { get; set; }
        public int cantidad_en_stock { get; set; }
        public Nullable<double> precio_De_Abastesimiento { get; set; }
    
        public virtual categorias categorias { get; set; }
    }
}
